# nvfetcher.toml
[manix]
src.github   = "mlvzk/manix"
fetch.github = "mlvzk/manix"

[decay-gtk]
src.git   = "https://github.com/decaycs/decay-gtk"
fetch.git = "https://github.com/decaycs/decay-gtk"

[heirline-nvim]
src.git   = "https://github.com/rebelot/heirline.nvim"
fetch.git = "https://github.com/rebelot/heirline.nvim"
