# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  decay-gtk = {
    pname = "decay-gtk";
    version = "19a60e6f83f5c8193ce3b44f693d8cd8d17eef53";
    src = fetchgit {
      url = "https://github.com/decaycs/decay-gtk";
      rev = "19a60e6f83f5c8193ce3b44f693d8cd8d17eef53";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-i6crTKc0NcS/u9edjZjFJItxcxvW5BMK0cvPuBvP/Aw=";
    };
  };
  manix = {
    pname = "manix";
    version = "v0.6.3";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "v0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
  };
}
